//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_APP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Krivosheev_zadanieEntities1 : DbContext
    {
        private static Krivosheev_zadanieEntities1 _context;

        public static Krivosheev_zadanieEntities1 GetContext()
        {
            if (_context == null)
                _context = new Krivosheev_zadanieEntities1();
            return _context;
        }
        public Krivosheev_zadanieEntities1()
            : base("name=Krivosheev_zadanieEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Компьютер> Компьютер { get; set; }
        public virtual DbSet<Программа> Программа { get; set; }
        public virtual DbSet<Установка> Установка { get; set; }
    }
}
