//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Установка
    {
        public int id { get; set; }
        public Nullable<int> код_программы { get; set; }
        public Nullable<int> номер_компьютера { get; set; }
        public Nullable<System.DateTime> дата_установки { get; set; }
        public string режим_установки { get; set; }
    
        public virtual Компьютер Компьютер { get; set; }
        public virtual Программа Программа { get; set; }
    }
}
